image: ruby:3.3

pages:
  script:
    - rm Gemfile.lock
    - gem install bundle
    - gem install minima
    - gem install jekyll-scholar
    - bundle install
    - bundle update minima
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public


