# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: Language and Computation in Neural Systems
email: lacns@mpi.nl
description: >- # this means to ignore newlines until "baseurl:"
  We are an international group of scientists consisting of linguists, cognitive scientists, cognitive neuroscientists, computational neuroscientists, computational modellers, computational scientists, and engineers. We are interested in how the mind and brain processes speech and language.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: lacns

# Build settings
theme: minima
plugins:
  - jekyll-feed

# read in static image files
image_serve_path: "/assets/images/" # <img src="{{ site.image_serve_path }}/projects/img.jpg">

# what is this, should be modified
include:
 - _pages
 - _redirects

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass output
sass:
  style: compressed # :nested :compact :expanded :compressed

# generate publications list
gems:
  - "jekyll/scholar"
  - jekyll-font-awesome-sass

scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  group_by: none
  group_order: ascending
  source: ./_data
  bibliography: lacns.bib
  bibliography_template: ""
  replace_strings: true
  join_strings:    true
  query: "@*"

# Structure
navigation:
  - title: Projects
    url: /
  - title: Fonts
    url: /fonts
  - title: About
    url: /about
  - title: Contact
    url: /contact

permalink: /:title/

# Configure site collections
collections:
  people:
    output: true
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - temp
  - Gemfile
  - Gemfile.lock
  - LICENSE
