name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensures all branches are fetched

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3' # Set this to the version you need

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        #rm Gemfile.lock
        gem install bundle
        #gem install minima
        #gem install jekyll-scholar
        bundle install
        #bundle update minima

    - name: Build and run local server
      run: |
        bundle exec jekyll build
        # bundle exec jekyll serve --livereload --detach
        # Normally, we don't run `jekyll serve` on CI as it will hang indefinitely.
        # If you want to run tests, replace the line below with your test commands.

